Repository SOPT-29th-JointSeminar-9/Client-iOS, pull requests merged in 2021-12, with the labels that each got.

#22 Feat/21 set moya
  SOPT-29th-JointSeminar-9-Client-iOS/Podfile
  SOPT-29th-JointSeminar-9-Client-iOS/Podfile.lock
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIEssentials/APIConstants.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIEssentials/NetworkResult.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIModels/MusicHugDetailData.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIServices/MusicHugAPI.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIServices/MusicHugService.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Storyboard/PopUpVC.swift
Labels: 🤍 지은 🤍, 기능⚙️

#25 ✨[FEAT] : 뮤직허그 방 생성(Create) API 연결
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIServices/MusicHugAPI.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Storyboard/PopUpVC.swift
Labels: 🤍 지은 🤍, 서버통신 📡

#26 [Feat/23] 뮤직허그 디테일뷰(채팅뷰) GET 서버통신 완료!
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/View/BottomMusicBarView.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Cell/MusicPlayChatCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Controller/ChatMusicBottomVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Controller/ChatVC.swift
Labels: 🤍 지은 🤍, 💬 채팅 뷰, 기능⚙️, 서버통신 📡

#28 ➕[ADD] : 파일 전송
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Struct/MenuContentData.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/View/BottomMusicBarView.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIModels/MusicHugDetailData.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIModels/NewData.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIServices/MusicHugAPI.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Cell/MusicPlayChatCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuPageCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/NewMenuTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/NewTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Controller/MusicHugVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/TabList/Storyboard/Base.lproj/Main.storyboard
Labels: 도움 필요💡, ❤️ 주민 ❤️, ℹ️ 전체메뉴 뷰

#30 ✅[CHORE] : Null값 고정데이터로 처리 및 Homejudge함수 추가
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIModels/MusicHugDetailData.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIServices/MusicHugAPI.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/NewMenuTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/NewMenuTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/NewTVC.swift
Labels: 🤍 지은 🤍, 서버통신 📡

#31 [Feat/27] : 최신부분 서버통신으로 데이터 가져오기
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIModels/NewData.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/NewMenuTVC.swift
Labels: ❤️ 주민 ❤️, 서버통신 📡
