Repository SOPT-29th-JointSeminar-9/Client-iOS, pull requests merged in 2021-11, with the labels that each got.

#5 [Feat/2] 하단 음악재생 바(BottomMusicBar) UI 구현 완료 ✨
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Extension/UILabel+.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Struct/Identifiers.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/View/BottomMusicBarView.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/View/View.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Controller/ChatMusicBottomVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Controller/ChatVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Storyboard/Chat.storyboard
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/TabBar/Controller/GenieTBC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatImgMusic.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatImgMusic.imageset/chatImgMusic.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatImgMusic.imageset/chatImgMusic@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatImgMusic.imageset/chatImgMusic@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcNext.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcNext.imageset/mainIcNext.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcNext.imageset/mainIcNext@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcNext.imageset/mainIcNext@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPause.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPause.imageset/Group 17.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPause.imageset/Group 17@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPause.imageset/Group 17@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPlay.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPlay.imageset/mainIcPlay.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPlay.imageset/mainIcPlay@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPlay.imageset/mainIcPlay@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPlaylist.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPlaylist.imageset/mainIcPlaylist.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPlaylist.imageset/mainIcPlaylist@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPlaylist.imageset/mainIcPlaylist@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPrevious.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPrevious.imageset/mainIcPrevious.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPrevious.imageset/mainIcPrevious@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcPrevious.imageset/mainIcPrevious@3x.png
Labels: 🤍 지은 🤍, 기능⚙️, 📱재사용 뷰

#8 [Feat/4] 상단 네비게이션바, UI 구현 완료 ✨
  SOPT-29th-JointSeminar-9-Client-iOS/Podfile.lock
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Extension/NSObject + reusableIdentifier.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Struct/Identifiers.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Struct/MenuContentData.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuCVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuPageCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuPageCVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/b.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/MenuHomeTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/MenuHomeTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/a.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Controller/CustomMenuTabBar.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Controller/MenuNVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Controller/MenuVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Controller/MusicHugVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Storyboard/Menu.storyboard
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/TabBar/Controller/GenieTBC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/main_ic_back.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/main_ic_back.imageset/main_ic_back.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/main_ic_back.imageset/main_ic_back@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/main_ic_back.imageset/main_ic_back@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/main_img_profile.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/main_img_profile.imageset/main_img_profile.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/main_img_profile.imageset/main_img_profile@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/main_img_profile.imageset/main_img_profile@3x.png
Labels: ❤️ 주민 ❤️, ℹ️ 전체메뉴 뷰, 기능⚙️

#9 ✅[CHORE] : 메인뷰 실시간 인기 UI 구성
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Struct/Identifiers.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Struct/MenuContentData.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Storyboard/Chat.storyboard
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/ButtonTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/ButtonTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuPageCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuPageCVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/PopularCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/PopularCVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/MenuHomeTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/TabBar/Controller/GenieTBC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/iosMainBtnCreate.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/iosMainBtnCreate.imageset/iosMainBtnCreate.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/iosMainBtnCreate.imageset/iosMainBtnCreate@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/iosMainBtnCreate.imageset/iosMainBtnCreate@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/main_crown.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/main_crown.imageset/main_crown.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/main_crown.imageset/main_crown@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/main_crown.imageset/main_crown@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/PopularMenuTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/PopularMenuTVC.xib
Labels: ❤️ 주민 ❤️, ℹ️ 전체메뉴 뷰, 기능⚙️

#10 [Feat] chatting UI 구현 완료
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Class/BaseCell.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Class/BasePaddingLabel.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Class/Class.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Extension/String+.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Extension/UIColor+Additions.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Extension/UIView+.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Struct/Identifiers.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/View/BottomTextingAreaView.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/View/MusicHugNaviBarView.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Network/APIModels/MessageData.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Cell/ChatHeaderCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Cell/CounterpartChatCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Cell/MusicPlayChatCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Cell/MyChatCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Controller/ChatVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcDown.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcDown.imageset/chatIcDown.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcDown.imageset/chatIcDown@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcDown.imageset/chatIcDown@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcHambuger.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcHambuger.imageset/chatIcHambuger.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcHambuger.imageset/chatIcHambuger@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcHambuger.imageset/chatIcHambuger@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcSearch.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcSearch.imageset/chatIcSearch.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcSearch.imageset/chatIcSearch@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcSearch.imageset/chatIcSearch@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcShare.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcShare.imageset/chatIcShare.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcShare.imageset/chatIcShare@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatIcShare.imageset/chatIcShare@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatImgProfile.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatImgProfile.imageset/chatImgProfile.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatImgProfile.imageset/chatImgProfile@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chatImgProfile.imageset/chatImgProfile@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chat_chatbubble.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chat_chatbubble.imageset/chat_chatbubble.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chat_chatbubble.imageset/chat_chatbubble@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/chat_chatbubble.imageset/chat_chatbubble@3x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/colorset/chatBackgroundGray.colorset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/colorset/chatTextGray.colorset/Contents.json
Labels: 🤍 지은 🤍, 💬 채팅 뷰, 기능⚙️

#11 [Feat/7] 팝업뷰와 화면전환 구현
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Struct/Identifiers.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuPageCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/ButtonTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/ButtonTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/PopularMenuTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/PopularMenuTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Controller/MusicHugVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Storyboard/PopUp.storyboard
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Storyboard/PopUpVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/create_img_profile.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/create_img_profile.imageset/create_img_profile.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/create_img_profile.imageset/create_img_profile@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/create_img_profile.imageset/create_img_profile@3x.png
Labels: ❤️ 주민 ❤️, ℹ️ 전체메뉴 뷰, 기능⚙️

#14 [Feat/12] 팝업VC에서 설정한 방 이름 ChatVC와 연결
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Extension/Notification.Name.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/View/MusicHugNaviBarView.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Cell/ChatHeaderCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Cell/CounterpartChatCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Cell/MusicPlayChatCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Cell/MyChatCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Controller/ChatVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Storyboard/Chat.storyboard
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Storyboard/PopUp.storyboard
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Storyboard/PopUpVC.swift
Labels: 🤍 지은 🤍, ℹ️ 전체메뉴 뷰, 💬 채팅 뷰, 기능⚙️

#15 ⚡️[IMPROVE] : 개설하기 버튼 수정
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuPageCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/ButtonTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/ButtonTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Controller/MusicHugVC.swift
Labels: ❤️ 주민 ❤️, ℹ️ 전체메뉴 뷰

#17 [Feat/16] 최신 UI 구현 완료
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Extension/UIColor+Additions.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Struct/Identifiers.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Struct/MenuContentData.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuPageCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuPageCVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/NewMenuTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/NewMenuTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/NewTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/NewTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/PopularMenuTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcVolumebar.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcVolumebar.imageset/mainIcVolumebar.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcVolumebar.imageset/mainIcVolumebar@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcVolumebar.imageset/mainIcVolumebar@3x.png
Labels: ❤️ 주민 ❤️, ℹ️ 전체메뉴 뷰, 기능⚙️

#19 [Feat/18] 맨위로버튼 추가, 헤더 수정
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS.xcodeproj/project.pbxproj
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Struct/Identifiers.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/Struct/MenuContentData.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuPageCVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/CVC/MenuPageCVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/BottomEmptyTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/BottomEmptyTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/NewMenuTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/NewTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/PopularMenuTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/PopularMenuTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/UpButtonTVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Cell/TVC/UpButtonTVC.xib
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcUp.imageset/Contents.json
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcUp.imageset/mainIcUp.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcUp.imageset/mainIcUp@2x.png
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Support/Assets.xcassets/mainIcUp.imageset/mainIcUp@3x.png
Labels: ❤️ 주민 ❤️, ℹ️ 전체메뉴 뷰, 기능⚙️

#20 ✅[CHORE] : ChatBottomMusicBar 구현
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/View/BottomMusicBarView.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/View/BottomTextingAreaView.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Global/View/MusicHugNaviBarView.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Controller/ChatMusicBottomVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Chat/Controller/ChatVC.swift
  SOPT-29th-JointSeminar-9-Client-iOS/SOPT-29th-JointSeminar-9-Client-iOS/Screen/Menu/Storyboard/Menu.storyboard
Labels: 🤍 지은 🤍, 💬 채팅 뷰, 기능⚙️
